project_id = "tvdromfazjzargvesruq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://featherbiz.io"
additional_redirect_urls = ["https://featherbiz.io", "https://lovable.app"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_captcha_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.email.smtp]
host = "smtp.resend.com"
port = 587
user = "resend"
admin_email = "admin@featherbiz.io"
sender_name = "FeatherBiz"

[auth.sms]
enable_signup = false
enable_confirmations = false

[auth.external.apple]
enabled = false
client_id = ""
secret = ""

[auth.external.azure]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.bitbucket]
enabled = false
client_id = ""
secret = ""

[auth.external.discord]
enabled = false
client_id = ""
secret = ""

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[auth.external.gitlab]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.keycloak]
enabled = false
client_id = ""
secret = ""
url = ""

[auth.external.linkedin]
enabled = false
client_id = ""
secret = ""

[auth.external.notion]
enabled = false
client_id = ""
secret = ""

[auth.external.twitch]
enabled = false
client_id = ""
secret = ""

[auth.external.twitter]
enabled = false
client_id = ""
secret = ""

[auth.external.slack]
enabled = false
client_id = ""
secret = ""

[auth.external.spotify]
enabled = false
client_id = ""
secret = ""

[auth.external.workos]
enabled = false
client_id = ""
secret = ""

[auth.external.zoom]
enabled = false
client_id = ""
secret = ""

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"

[analytics]
enabled = false
port = 54327
vector_port = 54328

[functions.ai-faq-assistant]
verify_jwt = true

[functions.appointments-api]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.extract-receipt-data]
verify_jwt = true

[functions.generate-contract-ai]
verify_jwt = true

[functions.send-admin-emails]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-document-email]
verify_jwt = true

[functions.send-meeting-invitations]
verify_jwt = true

[functions.send-meeting-reminders]
verify_jwt = false

[functions.send-payment-confirmation]
verify_jwt = false

[functions.send-receipt-email]
verify_jwt = true

[functions.send-user-email]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.signnow-auth]
verify_jwt = true

[functions.signnow-download]
verify_jwt = true

[functions.signnow-invite]
verify_jwt = true

[functions.signnow-status]
verify_jwt = true

[functions.signnow-upload]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = true

[functions.verify-client-portal-access]
verify_jwt = false

[functions.list-stripe-prices]
verify_jwt = false

[functions.featherbot-assistant]
verify_jwt = false

[functions.sync-stripe-pricing]
verify_jwt = false