// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvdromfazjzargvesruq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2ZHJvbWZhemp6YXJndmVzcnVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTkxMzAsImV4cCI6MjA2NDA3NTEzMH0.o2qM4KTfXwPia6lViwz4rrX4uh_ovMQ7BCtPIZIBoX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);